const ACTION_TYPES = 
{
    TOGGLE_DRAWER: 'TOGGLE_DRAWER',

    TOGGLE_DASHBOARDS: 'TOGGLE_DASHBOARDS',
    SELECT_MAIN_DASHBOARD: 'SELECT_MAIN_DASHBOARD',
    SELECT_PAYROLL_DASHBOARD: 'SELECT_PAYROLL_DASHBOARD',
    SELECT_DOUBLE_ENTRY_DASHBOARD: 'SELECT_DOUBLE_ENTRY_DASHBOARD',

    TOGGLE_DOUBLE_ENTRY: 'TOGGLE_DOUBLE_ENTRY',
    SELECT_DOUBLE_ENTRY_CHART_OF_ACCOUNT: 'SELECT_DOUBLE_ENTRY_CHART_OF_ACCOUNT',
    SELECT_DOUBLE_ENTRY_CHART_OF_ACCOUNT_TYPE: 'SELECT_DOUBLE_ENTRY_CHART_OF_ACCOUNT_TYPE',
    SELECT_DOUBLE_ENTRY_JOURNAL_ENTRY: 'SELECT_DOUBLE_ENTRY_JOURNAL_ENTRY',

    TOGGLE_ITEMS: 'SELECT_ITEMS',
    SELECT_ITEMS_ITEM: 'SELECT_ITEMS_ITEM',
    SELECT_ITEMS_CATEGORY: 'SELECT_ITEMS_CATEGORY',
    SELECT_ITEMS_DISCOUNT: 'SELECT_ITEMS_DISCOUNT',

    TOGGLE_INVENTORY: 'TOGGLE_INVENTORY',
    SELECT_INVENTORY_STOCK_ADJUSTMENT: 'SELECT_INVENTORY_STOCK_ADJUSTMENT',
    SELECT_INVENTORY_WAREHOUSE: 'SELECT_INVENTORY_WAREHOUSE',

    TOGGLE_SALES: 'TOGGLE_SALES',
    SELECT_SALES_DEBIT_NOTE: 'SELECT_SALES_DEBIT_NOTE',
    SELECT_SALES_INVOICE: 'SELECT_SALES_INVOICE',
    SELECT_SALES_ESTIMATE: 'SELECT_SALES_ESTIMATE',
    SELECT_SALES_REVENUE: 'SELECT_SALES_REVENUE',
    SELECT_SALES_CUSTOMER: 'SELECT_SALES_CUSTOMER',

    TOGGLE_PURCHASES: 'TOGGLE_PURCHASES',
    SELECT_PURCHASES_CREDIT_NOTE: 'SELECT_PURCHASES_CREDIT_NOTE',
    SELECT_PURCHASES_BILL: 'SELECT_PURCHASES_BILL',
    SELECT_PURCHASES_PAYMENT: 'SELECT_PURCHASES_PAYMENT',
    SELECT_PURCHASES_VENDOR: 'SELECT_PURCHASES_VENDOR',

    TOGGLE_BANKING: 'TOGGLE_BANKING',
    SELECT_BANKING_ACCOUNT: 'SELECT_BANKING_ACCOUNT',
    SELECT_BANKING_TRANSFER: 'SELECT_BANKING_TRANSFER',
    SELECT_BANKING_TRANSACTION: 'SELECT_BANKING_TRANSACTION',
    SELECT_BANKING_RECONCILIATION: 'SELECT_BANKING_RECONCILIATION',

    TOGGLE_PAYROLL: 'TOGGLE_PAYROLL',
    SELECT_PAYROLL_PAY_CALENDAR: 'SELECT_PAYROLL_PAY_CALENDAR',
    SELECT_PAYROLL_RUN_PAYROLL: 'SELECT_PAYROLL_RUN_PAYROLL',

    EMPLOYEES: 'EMPLOYEES',

    REPORTS: 'REPORTS',
    SETTINGS: 'SETTINGS'
};

export default ACTION_TYPES