const ACTION_TYPES = 
{
    GET_CHART_OF_ACCOUNTS_START: 'GET_CHART_OF_ACCOUNTS_START',
    GET_CHART_OF_ACCOUNTS_SUCCESS: 'GET_CHART_OF_ACCOUNTS_SUCCESS',
    GET_CHART_OF_ACCOUNTS_FAILED: 'GET_CHART_OF_ACCOUNTS_FAILED',
    
    CREATE_CHART_OF_ACCOUNT_START: 'CREATE_CHART_OF_ACCOUNT_START',
    CREATE_CHART_OF_ACCOUNT_SUCCESS: 'CREATE_CHART_OF_ACCOUNT_SUCCESS',
    CREATE_CHART_OF_ACCOUNT_FAILED: 'CREATE_CHART_OF_ACCOUNT_FAILED',

    UPDATE_CHART_OF_ACCOUNT_START: 'UPDATE_CHART_OF_ACCOUNT_START',
    UPDATE_CHART_OF_ACCOUNT_SUCCESS: 'UPDATE_CHART_OF_ACCOUNT_SUCCESS',
    UPDATE_CHART_OF_ACCOUNT_FAILED: 'UPDATE_CHART_OF_ACCOUNT_FAILED',

    DESTROY_CHART_OF_ACCOUNTS_START: 'DESTROY_CHART_OF_ACCOUNTS_START',
    DESTROY_CHART_OF_ACCOUNTS_SUCCESS: 'DESTROY_CHART_OF_ACCOUNTS_SUCCESS',
    DESTROY_CHART_OF_ACCOUNTS_FAILED: 'DESTROY_CHART_OF_ACCOUNTS_FAILED',
};

export default ACTION_TYPES;