const ACTION_TYPES = 
{
    GET_ACCOUNTS_START: 'GET_ACCOUNTS_START',
    GET_ACCOUNTS_SUCCESS: 'GET_ACCOUNTS_SUCCESS',
    GET_ACCOUNTS_FAILED: 'GET_ACCOUNTS_FAILED',
    
    CREATE_ACCOUNT_START: 'CREATE_ACCOUNT_START',
    CREATE_ACCOUNT_SUCCESS: 'CREATE_ACCOUNT_SUCCESS',
    CREATE_ACCOUNT_FAILED: 'CREATE_ACCOUNT_FAILED',

    UPDATE_ACCOUNT_START: 'UPDATE_ACCOUNT_START',
    UPDATE_ACCOUNT_SUCCESS: 'UPDATE_ACCOUNT_SUCCESS',
    UPDATE_ACCOUNT_FAILED: 'UPDATE_ACCOUNT_FAILED',

    DESTROY_ACCOUNTS_START: 'DESTROY_ACCOUNTS_START',
    DESTROY_ACCOUNTS_SUCCESS: 'DESTROY_ACCOUNTS_SUCCESS',
    DESTROY_ACCOUNTS_FAILED: 'DESTROY_ACCOUNTS_FAILED',
};

export default ACTION_TYPES;