const ACTION_TYPES = 
{
    GET_RUN_PAYROLLS_START: 'GET_RUN_PAYROLLS_START',
    GET_RUN_PAYROLLS_SUCCESS: 'GET_RUN_PAYROLLS_SUCCESS',
    GET_RUN_PAYROLLS_FAILED: 'GET_RUN_PAYROLLS_FAILED',
    
    CREATE_RUN_PAYROLL_START: 'CREATE_RUN_PAYROLL_START',
    CREATE_RUN_PAYROLL_SUCCESS: 'CREATE_RUN_PAYROLL_SUCCESS',
    CREATE_RUN_PAYROLL_FAILED: 'CREATE_RUN_PAYROLL_FAILED',

    APPROVE_RUN_PAYROLL_START: 'APPROVE_RUN_PAYROLL_START',
    APPROVE_RUN_PAYROLL_SUCCESS: 'APPROVE_RUN_PAYROLL_SUCCESS',
    APPROVE_RUN_PAYROLL_FAILED: 'APPROVE_RUN_PAYROLL_FAILED',

    UPDATE_RUN_PAYROLL_START: 'UPDATE_RUN_PAYROLL_START',
    UPDATE_RUN_PAYROLL_SUCCESS: 'UPDATE_RUN_PAYROLL_SUCCESS',
    UPDATE_RUN_PAYROLL_FAILED: 'UPDATE_RUN_PAYROLL_FAILED',

    DESTROY_RUN_PAYROLLS_START: 'DESTROY_RUN_PAYROLLS_START',
    DESTROY_RUN_PAYROLLS_SUCCESS: 'DESTROY_RUN_PAYROLLS_SUCCESS',
    DESTROY_RUN_PAYROLLS_FAILED: 'DESTROY_RUN_PAYROLLS_FAILED',
};

export default ACTION_TYPES;