const ACTION_TYPES = 
{
    GET_ACCESS_RIGHTS_START: 'GET_ACCESS_RIGHTS_START',
    GET_ACCESS_RIGHTS_SUCCESS: 'GET_ACCESS_RIGHTS_SUCCESS',
    GET_ACCESS_RIGHTS_FAILED: 'GET_ACCESS_RIGHTS_FAILED',
    
    CREATE_ACCESS_RIGHT_START: 'CREATE_ACCESS_RIGHT_START',
    CREATE_ACCESS_RIGHT_SUCCESS: 'CREATE_ACCESS_RIGHT_SUCCESS',
    CREATE_ACCESS_RIGHT_FAILED: 'CREATE_ACCESS_RIGHT_FAILED',

    UPDATE_ACCESS_RIGHT_START: 'UPDATE_ACCESS_RIGHT_START',
    UPDATE_ACCESS_RIGHT_SUCCESS: 'UPDATE_ACCESS_RIGHT_SUCCESS',
    UPDATE_ACCESS_RIGHT_FAILED: 'UPDATE_ACCESS_RIGHT_FAILED',

    DESTROY_ACCESS_RIGHTS_START: 'DESTROY_ACCESS_RIGHTS_START',
    DESTROY_ACCESS_RIGHTS_SUCCESS: 'DESTROY_ACCESS_RIGHTS_SUCCESS',
    DESTROY_ACCESS_RIGHTS_FAILED: 'DESTROY_ACCESS_RIGHTS_FAILED',
};

export default ACTION_TYPES;