const ACTION_TYPES = 
{
    GET_WAREHOUSES_START: 'GET_WAREHOUSES_START',
    GET_WAREHOUSES_SUCCESS: 'GET_WAREHOUSES_SUCCESS',
    GET_WAREHOUSES_FAILED: 'GET_WAREHOUSES_FAILED',
    
    CREATE_WAREHOUSE_START: 'CREATE_WAREHOUSE_START',
    CREATE_WAREHOUSE_SUCCESS: 'CREATE_WAREHOUSE_SUCCESS',
    CREATE_WAREHOUSE_FAILED: 'CREATE_WAREHOUSE_FAILED',

    UPDATE_WAREHOUSE_START: 'UPDATE_WAREHOUSE_START',
    UPDATE_WAREHOUSE_SUCCESS: 'UPDATE_WAREHOUSE_SUCCESS',
    UPDATE_WAREHOUSE_FAILED: 'UPDATE_WAREHOUSE_FAILED',

    DESTROY_WAREHOUSES_START: 'DESTROY_WAREHOUSES_START',
    DESTROY_WAREHOUSES_SUCCESS: 'DESTROY_WAREHOUSES_SUCCESS',
    DESTROY_WAREHOUSES_FAILED: 'DESTROY_WAREHOUSES_FAILED',
};

export default ACTION_TYPES;