const ACTION_TYPES = 
{
    GET_ESTIMATE_INVOICES_START: 'GET_ESTIMATE_INVOICES_START',
    GET_ESTIMATE_INVOICES_SUCCESS: 'GET_ESTIMATE_INVOICES_SUCCESS',
    GET_ESTIMATE_INVOICES_FAILED: 'GET_ESTIMATE_INVOICES_FAILED',
    
    CREATE_ESTIMATE_INVOICE_START: 'CREATE_ESTIMATE_INVOICE_START',
    CREATE_ESTIMATE_INVOICE_SUCCESS: 'CREATE_ESTIMATE_INVOICE_SUCCESS',
    CREATE_ESTIMATE_INVOICE_FAILED: 'CREATE_ESTIMATE_INVOICE_FAILED',

    CONVERT_TO_INVOICE_START: 'CONVERT_TO_INVOICE_START',
    CONVERT_TO_INVOICE_SUCCESS: 'CONVERT_TO_INVOICE_SUCCESS',
    CONVERT_TO_INVOICE_FAILED: 'CONVERT_TO_INVOICE_FAILED',

    MAIL_ESTIMATE_INVOICE_CUSTOMER_START: 'MAIL_ESTIMATE_INVOICE_CUSTOMER_START',
    MAIL_ESTIMATE_INVOICE_CUSTOMER_SUCCESS: 'MAIL_ESTIMATE_INVOICE_CUSTOMER_SUCCESS',
    MAIL_ESTIMATE_INVOICE_CUSTOMER_FAILED: 'MAIL_ESTIMATE_INVOICE_CUSTOMER_FAILED',

    MARK_ESTIMATE_INVOICE_AS_APPROVED_START: 'MARK_ESTIMATE_INVOICE_AS_APPROVED_START',
    MARK_ESTIMATE_INVOICE_AS_APPROVED_SUCCESS: 'MARK_ESTIMATE_INVOICE_AS_APPROVED_SUCCESS',
    MARK_ESTIMATE_INVOICE_AS_APPROVED_FAILED: 'MARK_ESTIMATE_INVOICE_AS_APPROVED_FAILED',

    MARK_ESTIMATE_INVOICE_AS_REFUSED_START: 'MARK_ESTIMATE_INVOICE_AS_REFUSED_START',
    MARK_ESTIMATE_INVOICE_AS_REFUSED_SUCCESS: 'MARK_ESTIMATE_INVOICE_AS_REFUSED_SUCCESS',
    MARK_ESTIMATE_INVOICE_AS_REFUSED_FAILED: 'MARK_ESTIMATE_INVOICE_AS_REFUSED_FAILED',

    UPDATE_ESTIMATE_INVOICE_START: 'UPDATE_ESTIMATE_INVOICE_START',
    UPDATE_ESTIMATE_INVOICE_SUCCESS: 'UPDATE_ESTIMATE_INVOICE_SUCCESS',
    UPDATE_ESTIMATE_INVOICE_FAILED: 'UPDATE_ESTIMATE_INVOICE_FAILED',

    DESTROY_ESTIMATE_INVOICES_START: 'DESTROY_ESTIMATE_INVOICES_START',
    DESTROY_ESTIMATE_INVOICES_SUCCESS: 'DESTROY_ESTIMATE_INVOICES_SUCCESS',
    DESTROY_ESTIMATE_INVOICES_FAILED: 'DESTROY_ESTIMATE_INVOICES_FAILED',
};

export default ACTION_TYPES;