const ACTION_TYPES = 
{
    GET_EXPENSE_CATEGORIES_START: 'GET_EXPENSE_CATEGORIES_START',
    GET_EXPENSE_CATEGORIES_SUCCESS: 'GET_EXPENSE_CATEGORIES_SUCCESS',
    GET_EXPENSE_CATEGORIES_FAILED: 'GET_EXPENSE_CATEGORIES_FAILED',
    
    CREATE_EXPENSE_CATEGORY_START: 'CREATE_EXPENSE_CATEGORY_START',
    CREATE_EXPENSE_CATEGORY_SUCCESS: 'CREATE_EXPENSE_CATEGORY_SUCCESS',
    CREATE_EXPENSE_CATEGORY_FAILED: 'CREATE_EXPENSE_CATEGORY_FAILED',

    UPDATE_EXPENSE_CATEGORY_START: 'UPDATE_EXPENSE_CATEGORY_START',
    UPDATE_EXPENSE_CATEGORY_SUCCESS: 'UPDATE_EXPENSE_CATEGORY_SUCCESS',
    UPDATE_EXPENSE_CATEGORY_FAILED: 'UPDATE_EXPENSE_CATEGORY_FAILED',

    DESTROY_EXPENSE_CATEGORIES_START: 'DESTROY_EXPENSE_CATEGORIES_START',
    DESTROY_EXPENSE_CATEGORIES_SUCCESS: 'DESTROY_EXPENSE_CATEGORIES_SUCCESS',
    DESTROY_EXPENSE_CATEGORIES_FAILED: 'DESTROY_EXPENSE_CATEGORIES_FAILED',
};

export default ACTION_TYPES;