const ACTION_TYPES = 
{
    GET_CUSTOMERS_START: 'GET_CUSTOMERS_START',
    GET_CUSTOMERS_SUCCESS: 'GET_CUSTOMERS_SUCCESS',
    GET_CUSTOMERS_FAILED: 'GET_CUSTOMERS_FAILED',
    
    CREATE_CUSTOMER_START: 'CREATE_CUSTOMER_START',
    CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS',
    CREATE_CUSTOMER_FAILED: 'CREATE_CUSTOMER_FAILED',

    UPDATE_CUSTOMER_START: 'UPDATE_CUSTOMER_START',
    UPDATE_CUSTOMER_SUCCESS: 'UPDATE_CUSTOMER_SUCCESS',
    UPDATE_CUSTOMER_FAILED: 'UPDATE_CUSTOMER_FAILED',

    DESTROY_CUSTOMERS_START: 'DESTROY_CUSTOMERS_START',
    DESTROY_CUSTOMERS_SUCCESS: 'DESTROY_CUSTOMERS_SUCCESS',
    DESTROY_CUSTOMERS_FAILED: 'DESTROY_CUSTOMERS_FAILED',
};

export default ACTION_TYPES;