const ACTION_TYPES = 
{
    GET_PAY_CALENDARS_START: 'GET_PAY_CALENDARS_START',
    GET_PAY_CALENDARS_SUCCESS: 'GET_PAY_CALENDARS_SUCCESS',
    GET_PAY_CALENDARS_FAILED: 'GET_PAY_CALENDARS_FAILED',
    
    CREATE_PAY_CALENDAR_START: 'CREATE_PAY_CALENDAR_START',
    CREATE_PAY_CALENDAR_SUCCESS: 'CREATE_PAY_CALENDAR_SUCCESS',
    CREATE_PAY_CALENDAR_FAILED: 'CREATE_PAY_CALENDAR_FAILED',

    UPDATE_PAY_CALENDAR_START: 'UPDATE_PAY_CALENDAR_START',
    UPDATE_PAY_CALENDAR_SUCCESS: 'UPDATE_PAY_CALENDAR_SUCCESS',
    UPDATE_PAY_CALENDAR_FAILED: 'UPDATE_PAY_CALENDAR_FAILED',

    DESTROY_PAY_CALENDARS_START: 'DESTROY_PAY_CALENDARS_START',
    DESTROY_PAY_CALENDARS_SUCCESS: 'DESTROY_PAY_CALENDARS_SUCCESS',
    DESTROY_PAY_CALENDARS_FAILED: 'DESTROY_PAY_CALENDARS_FAILED',
};

export default ACTION_TYPES;