const ACTION_TYPES = 
{
    GET_SALARY_BENEFITS_START: 'GET_SALARY_BENEFITS_START',
    GET_SALARY_BENEFITS_SUCCESS: 'GET_SALARY_BENEFITS_SUCCESS',
    GET_SALARY_BENEFITS_FAILED: 'GET_SALARY_BENEFITS_FAILED',
    
    CREATE_SALARY_BENEFIT_START: 'CREATE_SALARY_BENEFIT_START',
    CREATE_SALARY_BENEFIT_SUCCESS: 'CREATE_SALARY_BENEFIT_SUCCESS',
    CREATE_SALARY_BENEFIT_FAILED: 'CREATE_SALARY_BENEFIT_FAILED',

    UPDATE_SALARY_BENEFIT_START: 'UPDATE_SALARY_BENEFIT_START',
    UPDATE_SALARY_BENEFIT_SUCCESS: 'UPDATE_SALARY_BENEFIT_SUCCESS',
    UPDATE_SALARY_BENEFIT_FAILED: 'UPDATE_SALARY_BENEFIT_FAILED',

    DESTROY_SALARY_BENEFITS_START: 'DESTROY_SALARY_BENEFITS_START',
    DESTROY_SALARY_BENEFITS_SUCCESS: 'DESTROY_SALARY_BENEFITS_SUCCESS',
    DESTROY_SALARY_BENEFITS_FAILED: 'DESTROY_SALARY_BENEFITS_FAILED',
};

export default ACTION_TYPES;