const ACTION_TYPES = 
{
    GET_BANK_ACCOUNT_RECONCILIATIONS_START: 'GET_BANK_ACCOUNT_RECONCILIATIONS_START',
    GET_BANK_ACCOUNT_RECONCILIATIONS_SUCCESS: 'GET_BANK_ACCOUNT_RECONCILIATIONS_SUCCESS',
    GET_BANK_ACCOUNT_RECONCILIATIONS_FAILED: 'GET_BANK_ACCOUNT_RECONCILIATIONS_FAILED',
    
    CREATE_BANK_ACCOUNT_RECONCILIATION_START: 'CREATE_BANK_ACCOUNT_RECONCILIATION_START',
    CREATE_BANK_ACCOUNT_RECONCILIATION_SUCCESS: 'CREATE_BANK_ACCOUNT_RECONCILIATION_SUCCESS',
    CREATE_BANK_ACCOUNT_RECONCILIATION_FAILED: 'CREATE_BANK_ACCOUNT_RECONCILIATION_FAILED',

    UPDATE_BANK_ACCOUNT_RECONCILIATION_START: 'UPDATE_BANK_ACCOUNT_RECONCILIATION_START',
    UPDATE_BANK_ACCOUNT_RECONCILIATION_SUCCESS: 'UPDATE_BANK_ACCOUNT_RECONCILIATION_SUCCESS',
    UPDATE_BANK_ACCOUNT_RECONCILIATION_FAILED: 'UPDATE_BANK_ACCOUNT_RECONCILIATION_FAILED',

    REVERSE_BANK_ACCOUNT_RECONCILIATIONS_START: 'REVERSE_BANK_ACCOUNT_RECONCILIATIONS_START',
    REVERSE_BANK_ACCOUNT_RECONCILIATIONS_SUCCESS: 'REVERSE_BANK_ACCOUNT_RECONCILIATIONS_SUCCESS',
    REVERSE_BANK_ACCOUNT_RECONCILIATIONS_FAILED: 'REVERSE_BANK_ACCOUNT_RECONCILIATIONS_FAILED',
    
    DESTROY_BANK_ACCOUNT_RECONCILIATIONS_START: 'DESTROY_BANK_ACCOUNT_RECONCILIATIONS_START',
    DESTROY_BANK_ACCOUNT_RECONCILIATIONS_SUCCESS: 'DESTROY_BANK_ACCOUNT_RECONCILIATIONS_SUCCESS',
    DESTROY_BANK_ACCOUNT_RECONCILIATIONS_FAILED: 'DESTROY_BANK_ACCOUNT_RECONCILIATIONS_FAILED',
};

export default ACTION_TYPES;