const ACTION_TYPES = 
{
    GET_REVENUES_START: 'GET_REVENUES_START',
    GET_REVENUES_SUCCESS: 'GET_REVENUES_SUCCESS',
    GET_REVENUES_FAILED: 'GET_REVENUES_FAILED',
    
    CREATE_REVENUE_START: 'CREATE_REVENUE_START',
    CREATE_REVENUE_SUCCESS: 'CREATE_REVENUE_SUCCESS',
    CREATE_REVENUE_FAILED: 'CREATE_REVENUE_FAILED',

    UPDATE_REVENUE_START: 'UPDATE_REVENUE_START',
    UPDATE_REVENUE_SUCCESS: 'UPDATE_REVENUE_SUCCESS',
    UPDATE_REVENUE_FAILED: 'UPDATE_REVENUE_FAILED',

    DESTROY_REVENUES_START: 'DESTROY_REVENUES_START',
    DESTROY_REVENUES_SUCCESS: 'DESTROY_REVENUES_SUCCESS',
    DESTROY_REVENUES_FAILED: 'DESTROY_REVENUES_FAILED',
};

export default ACTION_TYPES;