const ACTION_TYPES = 
{
    GET_PAYMENT_METHODS_START: 'GET_PAYMENT_METHODS_START',
    GET_PAYMENT_METHODS_SUCCESS: 'GET_PAYMENT_METHODS_SUCCESS',
    GET_PAYMENT_METHODS_FAILED: 'GET_PAYMENT_METHODS_FAILED',
    
    CREATE_PAYMENT_METHOD_START: 'CREATE_PAYMENT_METHOD_START',
    CREATE_PAYMENT_METHOD_SUCCESS: 'CREATE_PAYMENT_METHOD_SUCCESS',
    CREATE_PAYMENT_METHOD_FAILED: 'CREATE_PAYMENT_METHOD_FAILED',

    UPDATE_PAYMENT_METHOD_START: 'UPDATE_PAYMENT_METHOD_START',
    UPDATE_PAYMENT_METHOD_SUCCESS: 'UPDATE_PAYMENT_METHOD_SUCCESS',
    UPDATE_PAYMENT_METHOD_FAILED: 'UPDATE_PAYMENT_METHOD_FAILED',

    DESTROY_PAYMENT_METHODS_START: 'DESTROY_PAYMENT_METHODS_START',
    DESTROY_PAYMENT_METHODS_SUCCESS: 'DESTROY_PAYMENT_METHODS_SUCCESS',
    DESTROY_PAYMENT_METHODS_FAILED: 'DESTROY_PAYMENT_METHODS_FAILED',
};

export default ACTION_TYPES;