const ACTION_TYPES = 
{
    GET_EMPLOYEES_START: 'GET_EMPLOYEES_START',
    GET_EMPLOYEES_SUCCESS: 'GET_EMPLOYEES_SUCCESS',
    GET_EMPLOYEES_FAILED: 'GET_EMPLOYEES_FAILED',
    
    CREATE_EMPLOYEE_START: 'CREATE_EMPLOYEE_START',
    CREATE_EMPLOYEE_SUCCESS: 'CREATE_EMPLOYEE_SUCCESS',
    CREATE_EMPLOYEE_FAILED: 'CREATE_EMPLOYEE_FAILED',

    UPDATE_EMPLOYEE_START: 'UPDATE_EMPLOYEE_START',
    UPDATE_EMPLOYEE_SUCCESS: 'UPDATE_EMPLOYEE_SUCCESS',
    UPDATE_EMPLOYEE_FAILED: 'UPDATE_EMPLOYEE_FAILED',

    DESTROY_EMPLOYEES_START: 'DESTROY_EMPLOYEES_START',
    DESTROY_EMPLOYEES_SUCCESS: 'DESTROY_EMPLOYEES_SUCCESS',
    DESTROY_EMPLOYEES_FAILED: 'DESTROY_EMPLOYEES_FAILED',
};

export default ACTION_TYPES;