const ACTION_TYPES = 
{
    GET_CHART_OF_ACCOUNT_TYPES_START: 'GET_CHART_OF_ACCOUNT_TYPES_START',
    GET_CHART_OF_ACCOUNT_TYPES_SUCCESS: 'GET_CHART_OF_ACCOUNT_TYPES_SUCCESS',
    GET_CHART_OF_ACCOUNT_TYPES_FAILED: 'GET_CHART_OF_ACCOUNT_TYPES_FAILED'
};

export default ACTION_TYPES;