const ACTION_TYPES = 
{
    GET_CHART_OF_ACCOUNT_TYPES_START: 'GET_CHART_OF_ACCOUNT_TYPES_START',
    GET_CHART_OF_ACCOUNT_TYPES_SUCCESS: 'GET_CHART_OF_ACCOUNT_TYPES_SUCCESS',
    GET_CHART_OF_ACCOUNT_TYPES_FAILED: 'GET_CHART_OF_ACCOUNT_TYPES_FAILED',
    
    CREATE_CHART_OF_ACCOUNT_TYPE_START: 'CREATE_CHART_OF_ACCOUNT_TYPE_START',
    CREATE_CHART_OF_ACCOUNT_TYPE_SUCCESS: 'CREATE_CHART_OF_ACCOUNT_TYPE_SUCCESS',
    CREATE_CHART_OF_ACCOUNT_TYPE_FAILED: 'CREATE_CHART_OF_ACCOUNT_TYPE_FAILED',

    UPDATE_CHART_OF_ACCOUNT_TYPE_START: 'UPDATE_CHART_OF_ACCOUNT_TYPE_START',
    UPDATE_CHART_OF_ACCOUNT_TYPE_SUCCESS: 'UPDATE_CHART_OF_ACCOUNT_TYPE_SUCCESS',
    UPDATE_CHART_OF_ACCOUNT_TYPE_FAILED: 'UPDATE_CHART_OF_ACCOUNT_TYPE_FAILED',

    DESTROY_CHART_OF_ACCOUNT_TYPES_START: 'DESTROY_CHART_OF_ACCOUNT_TYPES_START',
    DESTROY_CHART_OF_ACCOUNT_TYPES_SUCCESS: 'DESTROY_CHART_OF_ACCOUNT_TYPES_SUCCESS',
    DESTROY_CHART_OF_ACCOUNT_TYPES_FAILED: 'DESTROY_CHART_OF_ACCOUNT_TYPES_FAILED',
};

export default ACTION_TYPES;