const ACTION_TYPES = 
{
    GET_PAYMENTS_START: 'GET_PAYMENTS_START',
    GET_PAYMENTS_SUCCESS: 'GET_PAYMENTS_SUCCESS',
    GET_PAYMENTS_FAILED: 'GET_PAYMENTS_FAILED',
    
    CREATE_PAYMENT_START: 'CREATE_PAYMENT_START',
    CREATE_PAYMENT_SUCCESS: 'CREATE_PAYMENT_SUCCESS',
    CREATE_PAYMENT_FAILED: 'CREATE_PAYMENT_FAILED',

    UPDATE_PAYMENT_START: 'UPDATE_PAYMENT_START',
    UPDATE_PAYMENT_SUCCESS: 'UPDATE_PAYMENT_SUCCESS',
    UPDATE_PAYMENT_FAILED: 'UPDATE_PAYMENT_FAILED',

    DESTROY_PAYMENTS_START: 'DESTROY_PAYMENTS_START',
    DESTROY_PAYMENTS_SUCCESS: 'DESTROY_PAYMENTS_SUCCESS',
    DESTROY_PAYMENTS_FAILED: 'DESTROY_PAYMENTS_FAILED',
};

export default ACTION_TYPES;