const ACTION_TYPES = 
{
    GET_DISCOUNTS_START: 'GET_DISCOUNTS_START',
    GET_DISCOUNTS_SUCCESS: 'GET_DISCOUNTS_SUCCESS',
    GET_DISCOUNTS_FAILED: 'GET_DISCOUNTS_FAILED',
    
    CREATE_DISCOUNT_START: 'CREATE_DISCOUNT_START',
    CREATE_DISCOUNT_SUCCESS: 'CREATE_DISCOUNT_SUCCESS',
    CREATE_DISCOUNT_FAILED: 'CREATE_DISCOUNT_FAILED',

    UPDATE_DISCOUNT_START: 'UPDATE_DISCOUNT_START',
    UPDATE_DISCOUNT_SUCCESS: 'UPDATE_DISCOUNT_SUCCESS',
    UPDATE_DISCOUNT_FAILED: 'UPDATE_DISCOUNT_FAILED',

    DESTROY_DISCOUNTS_START: 'DESTROY_DISCOUNTS_START',
    DESTROY_DISCOUNTS_SUCCESS: 'DESTROY_DISCOUNTS_SUCCESS',
    DESTROY_DISCOUNTS_FAILED: 'DESTROY_DISCOUNTS_FAILED',
};

export default ACTION_TYPES;