const ACTION_TYPES = 
{
    GET_DEFAULT_SETTINGS_START: 'GET_DEFAULT_SETTINGS_START',
    GET_DEFAULT_SETTINGS_SUCCESS: 'GET_DEFAULT_SETTINGS_SUCCESS',
    GET_DEFAULT_SETTINGS_FAILED: 'GET_DEFAULT_SETTINGS_FAILED',

    UPDATE_DEFAULT_SETTINGS_START: 'UPDATE_DEFAULT_SETTINGS_START',
    UPDATE_DEFAULT_SETTINGS_SUCCESS: 'UPDATE_DEFAULT_SETTINGS_SUCCESS',
    UPDATE_DEFAULT_SETTINGS_FAILED: 'UPDATE_DEFAULT_SETTINGS_FAILED',
};

export default ACTION_TYPES;