const ACTION_TYPES = 
{
    GET_INVOICES_START: 'GET_INVOICES_START',
    GET_INVOICES_SUCCESS: 'GET_INVOICES_SUCCESS',
    GET_INVOICES_FAILED: 'GET_INVOICES_FAILED',
    
    CREATE_INVOICE_START: 'CREATE_INVOICE_START',
    CREATE_INVOICE_SUCCESS: 'CREATE_INVOICE_SUCCESS',
    CREATE_INVOICE_FAILED: 'CREATE_INVOICE_FAILED',

    MAIL_CUSTOMER_START: 'MAIL_CUSTOMER_START',
    MAIL_CUSTOMER_SUCCESS: 'MAIL_CUSTOMER_SUCCESS',
    MAIL_CUSTOMER_FAILED: 'MAIL_CUSTOMER_FAILED',

    MARK_INVOICE_AS_PAID_START: 'MARK_INVOICE_AS_PAID_START',
    MARK_INVOICE_AS_PAID_SUCCESS: 'MARK_INVOICE_AS_PAID_SUCCESS',
    MARK_INVOICE_AS_PAID_FAILED: 'MARK_INVOICE_AS_PAID_FAILED',

    INVOICE_PAYMENT_START: 'INVOICE_PAYMENT_START',
    INVOICE_PAYMENT_SUCCESS: 'INVOICE_PAYMENT_SUCCESS',
    INVOICE_PAYMENT_FAILED: 'INVOICE_PAYMENT_FAILED',

    UPDATE_INVOICE_START: 'UPDATE_INVOICE_START',
    UPDATE_INVOICE_SUCCESS: 'UPDATE_INVOICE_SUCCESS',
    UPDATE_INVOICE_FAILED: 'UPDATE_INVOICE_FAILED',

    CANCEL_INVOICE_START: 'CANCEL_INVOICE_START',
    CANCEL_INVOICE_SUCCESS: 'CANCEL_INVOICE_SUCCESS',
    CANCEL_INVOICE_FAILED: 'CANCEL_INVOICE_FAILED',

    DESTROY_INVOICES_START: 'DESTROY_INVOICES_START',
    DESTROY_INVOICES_SUCCESS: 'DESTROY_INVOICES_SUCCESS',
    DESTROY_INVOICES_FAILED: 'DESTROY_INVOICES_FAILED',
};

export default ACTION_TYPES;