const ACTION_TYPES = 
{
    GET_ITEMS_START: 'GET_ITEMS_START',
    GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS',
    GET_ITEMS_FAILED: 'GET_ITEMS_FAILED',
    
    CREATE_ITEM_START: 'CREATE_ITEM_START',
    CREATE_ITEM_SUCCESS: 'CREATE_ITEM_SUCCESS',
    CREATE_ITEM_FAILED: 'CREATE_ITEM_FAILED',

    UPDATE_ITEM_START: 'UPDATE_ITEM_START',
    UPDATE_ITEM_SUCCESS: 'UPDATE_ITEM_SUCCESS',
    UPDATE_ITEM_FAILED: 'UPDATE_ITEM_FAILED',

    DESTROY_ITEMS_START: 'DESTROY_ITEMS_START',
    DESTROY_ITEMS_SUCCESS: 'DESTROY_ITEMS_SUCCESS',
    DESTROY_ITEMS_FAILED: 'DESTROY_ITEMS_FAILED',
};

export default ACTION_TYPES;