const ACTION_TYPES = 
{
    GET_PAYROLLS_START: 'GET_PAYROLLS_START',
    GET_PAYROLLS_SUCCESS: 'GET_PAYROLLS_SUCCESS',
    GET_PAYROLLS_FAILED: 'GET_PAYROLLS_FAILED',
    
    CREATE_PAYROLL_START: 'CREATE_PAYROLL_START',
    CREATE_PAYROLL_SUCCESS: 'CREATE_PAYROLL_SUCCESS',
    CREATE_PAYROLL_FAILED: 'CREATE_PAYROLL_FAILED',

    APPROVE_PAYROLL_START: 'APPROVE_PAYROLL_START',
    APPROVE_PAYROLL_SUCCESS: 'APPROVE_PAYROLL_SUCCESS',
    APPROVE_PAYROLL_FAILED: 'APPROVE_PAYROLL_FAILED',

    UPDATE_PAYROLL_START: 'UPDATE_PAYROLL_START',
    UPDATE_PAYROLL_SUCCESS: 'UPDATE_PAYROLL_SUCCESS',
    UPDATE_PAYROLL_FAILED: 'UPDATE_PAYROLL_FAILED',

    DESTROY_PAYROLLS_START: 'DESTROY_PAYROLLS_START',
    DESTROY_PAYROLLS_SUCCESS: 'DESTROY_PAYROLLS_SUCCESS',
    DESTROY_PAYROLLS_FAILED: 'DESTROY_PAYROLLS_FAILED',
};

export default ACTION_TYPES;