const ACTION_TYPES = 
{
    GET_STOCK_ADJUSTMENTS_START: 'GET_STOCK_ADJUSTMENTS_START',
    GET_STOCK_ADJUSTMENTS_SUCCESS: 'GET_STOCK_ADJUSTMENTS_SUCCESS',
    GET_STOCK_ADJUSTMENTS_FAILED: 'GET_STOCK_ADJUSTMENTS_FAILED',
    
    CREATE_STOCK_ADJUSTMENT_START: 'CREATE_STOCK_ADJUSTMENT_START',
    CREATE_STOCK_ADJUSTMENT_SUCCESS: 'CREATE_STOCK_ADJUSTMENT_SUCCESS',
    CREATE_STOCK_ADJUSTMENT_FAILED: 'CREATE_STOCK_ADJUSTMENT_FAILED',

    UPDATE_STOCK_ADJUSTMENT_START: 'UPDATE_STOCK_ADJUSTMENT_START',
    UPDATE_STOCK_ADJUSTMENT_SUCCESS: 'UPDATE_STOCK_ADJUSTMENT_SUCCESS',
    UPDATE_STOCK_ADJUSTMENT_FAILED: 'UPDATE_STOCK_ADJUSTMENT_FAILED',

    DESTROY_STOCK_ADJUSTMENTS_START: 'DESTROY_STOCK_ADJUSTMENTS_START',
    DESTROY_STOCK_ADJUSTMENTS_SUCCESS: 'DESTROY_STOCK_ADJUSTMENTS_SUCCESS',
    DESTROY_STOCK_ADJUSTMENTS_FAILED: 'DESTROY_STOCK_ADJUSTMENTS_FAILED',
};

export default ACTION_TYPES;