const ACTION_TYPES = 
{
    GET_CATEGORIES_START: 'GET_CATEGORIES_START',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAILED: 'GET_CATEGORIES_FAILED',
    
    CREATE_CATEGORY_START: 'CREATE_CATEGORY_START',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAILED: 'CREATE_CATEGORY_FAILED',

    UPDATE_CATEGORY_START: 'UPDATE_CATEGORY_START',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAILED: 'UPDATE_CATEGORY_FAILED',

    DESTROY_CATEGORIES_START: 'DESTROY_CATEGORIES_START',
    DESTROY_CATEGORIES_SUCCESS: 'DESTROY_CATEGORIES_SUCCESS',
    DESTROY_CATEGORIES_FAILED: 'DESTROY_CATEGORIES_FAILED',
};

export default ACTION_TYPES;