const ACTION_TYPES = 
{
    GET_CONTRIBUTIONS_START: 'GET_CONTRIBUTIONS_START',
    GET_CONTRIBUTIONS_SUCCESS: 'GET_CONTRIBUTIONS_SUCCESS',
    GET_CONTRIBUTIONS_FAILED: 'GET_CONTRIBUTIONS_FAILED',
    
    CREATE_CONTRIBUTION_START: 'CREATE_CONTRIBUTION_START',
    CREATE_CONTRIBUTION_SUCCESS: 'CREATE_CONTRIBUTION_SUCCESS',
    CREATE_CONTRIBUTION_FAILED: 'CREATE_CONTRIBUTION_FAILED',

    UPDATE_CONTRIBUTION_START: 'UPDATE_CONTRIBUTION_START',
    UPDATE_CONTRIBUTION_SUCCESS: 'UPDATE_CONTRIBUTION_SUCCESS',
    UPDATE_CONTRIBUTION_FAILED: 'UPDATE_CONTRIBUTION_FAILED',

    DESTROY_CONTRIBUTIONS_START: 'DESTROY_CONTRIBUTIONS_START',
    DESTROY_CONTRIBUTIONS_SUCCESS: 'DESTROY_CONTRIBUTIONS_SUCCESS',
    DESTROY_CONTRIBUTIONS_FAILED: 'DESTROY_CONTRIBUTIONS_FAILED',
};

export default ACTION_TYPES;