const ACTION_TYPES = 
{

    CREATE_COMPANY_START: 'CREATE_COMPANY_START',
    CREATE_COMPANY_SUCCESS: 'CREATE_COMPANY_SUCCESS',
    CREATE_COMPANY_FAILED: 'CREATE_COMPANY_FAILED',

    UPDATE_COMPANY_START: 'UPDATE_COMPANY_START',
    UPDATE_COMPANY_SUCCESS: 'UPDATE_COMPANY_SUCCESS',
    UPDATE_COMPANY_FAILED: 'UPDATE_COMPANY_FAILED',

    DESTROY_COMPANIES_START: 'DESTROY_COMPANIES_START',
    DESTROY_COMPANIES_SUCCESS: 'DESTROY_COMPANIES_SUCCESS',
    DESTROY_COMPANIES_FAILED: 'DESTROY_COMPANIES_FAILED',
};

export default ACTION_TYPES;