const ACTION_TYPES = 
{
    GET_TAXES_START: 'GET_TAXES_START',
    GET_TAXES_SUCCESS: 'GET_TAXES_SUCCESS',
    GET_TAXES_FAILED: 'GET_TAXES_FAILED',
    
    CREATE_TAX_START: 'CREATE_TAX_START',
    CREATE_TAX_SUCCESS: 'CREATE_TAX_SUCCESS',
    CREATE_TAX_FAILED: 'CREATE_TAX_FAILED',

    UPDATE_TAX_START: 'UPDATE_TAX_START',
    UPDATE_TAX_SUCCESS: 'UPDATE_TAX_SUCCESS',
    UPDATE_TAX_FAILED: 'UPDATE_TAX_FAILED',

    DESTROY_TAXES_START: 'DESTROY_TAXES_START',
    DESTROY_TAXES_SUCCESS: 'DESTROY_TAXES_SUCCESS',
    DESTROY_TAXES_FAILED: 'DESTROY_TAXES_FAILED',
};

export default ACTION_TYPES;