const ACTION_TYPES = 
{
    GET_INCOME_CATEGORIES_START: 'GET_INCOME_CATEGORIES_START',
    GET_INCOME_CATEGORIES_SUCCESS: 'GET_INCOME_CATEGORIES_SUCCESS',
    GET_INCOME_CATEGORIES_FAILED: 'GET_INCOME_CATEGORIES_FAILED',
    
    CREATE_INCOME_CATEGORY_START: 'CREATE_INCOME_CATEGORY_START',
    CREATE_INCOME_CATEGORY_SUCCESS: 'CREATE_INCOME_CATEGORY_SUCCESS',
    CREATE_INCOME_CATEGORY_FAILED: 'CREATE_INCOME_CATEGORY_FAILED',

    UPDATE_INCOME_CATEGORY_START: 'UPDATE_INCOME_CATEGORY_START',
    UPDATE_INCOME_CATEGORY_SUCCESS: 'UPDATE_INCOME_CATEGORY_SUCCESS',
    UPDATE_INCOME_CATEGORY_FAILED: 'UPDATE_INCOME_CATEGORY_FAILED',

    DESTROY_INCOME_CATEGORIES_START: 'DESTROY_INCOME_CATEGORIES_START',
    DESTROY_INCOME_CATEGORIES_SUCCESS: 'DESTROY_INCOME_CATEGORIES_SUCCESS',
    DESTROY_INCOME_CATEGORIES_FAILED: 'DESTROY_INCOME_CATEGORIES_FAILED',
};

export default ACTION_TYPES;