const ACTION_TYPES = 
{
    GET_CURRENCIES_START: 'GET_CURRENCIES_START',
    GET_CURRENCIES_SUCCESS: 'GET_CURRENCIES_SUCCESS',
    GET_CURRENCIES_FAILED: 'GET_CURRENCIES_FAILED',
    
    CREATE_CURRENCY_START: 'CREATE_CURRENCY_START',
    CREATE_CURRENCY_SUCCESS: 'CREATE_CURRENCY_SUCCESS',
    CREATE_CURRENCY_FAILED: 'CREATE_CURRENCY_FAILED',

    UPDATE_CURRENCY_START: 'UPDATE_CURRENCY_START',
    UPDATE_CURRENCY_SUCCESS: 'UPDATE_CURRENCY_SUCCESS',
    UPDATE_CURRENCY_FAILED: 'UPDATE_CURRENCY_FAILED',

    DESTROY_CURRENCIES_START: 'DESTROY_CURRENCIES_START',
    DESTROY_CURRENCIES_SUCCESS: 'DESTROY_CURRENCIES_SUCCESS',
    DESTROY_CURRENCIES_FAILED: 'DESTROY_CURRENCIES_FAILED',
};

export default ACTION_TYPES;